### ISSUE TITLE
Setup a local identity provider for tests

### ISSUE THREAD

**Issue by mindtheme** [amosproj/amos2022ss08-openid-connect-doctor#17]
### User Story
1. As a user
2. I want the code to be tested
3. So that it works as expected

### Acceptance Criteria
- setup an identity provider (for example keycloak) running on the tester machine (or github) for testing purposes 
- the identity provider can be used for automated tests
- setup testing environment for unit tests etc.

**Comment by prebbe** [comment]
The current-project already contains the necessary dependencies to run unittests. 
I created a PR that sets up a simple CI-pipeline that builds and runs the unittests when a pull-request is created to ensure the tests are run at least once before changes are committed to the main-branch.
