### ISSUE TITLE
Get the public key from a file or the identity provider

### ISSUE THREAD

**Issue by mindtheme** [amosproj/amos2022ss08-openid-connect-doctor#34]
### User Story
1. As a user 
2. I need the tool to load a public key for signing from a file or get one from the identity provider
3. So that the validity of the token’s signature can be confirmed

### Acceptance Criteria
- Add the option to load a public key from a file
- If no file is provided, load the public key from the token identity provider

### Definition of Done

- Code has been tested
- Optional Logging has been added
- No errors (syntax, unit tests, etc.)
- Peer reviewed by at least one additional person
- Acceptance criteria met
- The code was merged into the main branch via pull request

**Comment by prebbe** [comment]
One question regarding the provided files: Are the public keys provided as a cert-file or as a json-file (similar to the output of the jwks-uri of the identity-provider)?

**Comment by prebbe** [comment]
Follow-up on my previous comment: The keymaterial will be provided as a PEM-file.
