### ISSUE TITLE
Include binary in the release

### ISSUE THREAD

**Issue by AnnaBilo** [amosproj/amos2022ss08-openid-connect-doctor#35]
### User Story

1. As a user
2. I want a binary included in the release
3. So that it can be tested without building it

### Acceptance Criteria

- Include Binary in the release

- Build Binary in CL-pipeline

### Definition of Done

- Code has been tested
- Optional Logging has been added
- No errors (syntax, unit tests, etc.)
- Peer reviewed by at least one additional person
- Acceptance criteria met
- The code was merged into the main branch via pull request

**Comment by skriesch** [comment]
I would suggest the usage of pkg: see https://blog.sivamuthukumar.com/vercel-pkg-nodejs
Our Github Actions file is here: https://github.com/amosproj/amos2022ss08-openid-connect-doctor/blob/main/.github/workflows/continous-integration.yml

**Comment by raghunandanarava** [comment]
This issue has been fixed. There were minor errors that were fixed, I have triggered the job and it generates the binaries and get attached to the release.
