### ISSUE TITLE
Add a protocol to the application

### ISSUE THREAD

**Issue by mindtheme** [amosproj/amos2022ss08-openid-connect-doctor#39]
### User Story
1. As a user 
2. I want a protocol displayed 
3. So that I see any errors that occur
### Acceptance Criteria
- Add a protocol
- Display the protocol as a part of the fronted
- Add option to write the protocols content into a file 
- Highlight the errors that occurred by, for example, changing the text color to red

### Definition of Done
- Code has been tested
- Optional Logging has been added
- No errors (syntax, unit tests, etc.)
- Peer reviewed by at least one additional person
- Acceptance criteria met
- The code was merged into the main branch via pull request

**Comment by raghunandanarava** [comment]
Different levels of logging can be used in accordance to the documentation

https://docs.nestjs.com/techniques/logger
