### ISSUE TITLE
Autostart browser on application start

### ISSUE THREAD

**Issue by mindtheme** [amosproj/amos2022ss08-openid-connect-doctor#54]
### User Story
1. As a user
2. I need my application to automatically launch the browser
3. So that I do not need to open the application window manually
### Acceptance Criteria
- Open a new browser tab, containing the application URL
- Start the browser, if it has not yet been started
### Definition of Done
- Code has been tested
- Optional Logging has been added
- No errors (syntax, unit tests, etc.)
- Peer reviewed by at least one additional person
- Acceptance criteria met
- The code was merged into the main branch via pull request

**Comment by skriesch** [comment]
It seems, that the easiest method is to integrate the package open. That solves also our cross-platform issue (discussed in the last meeting): https://github.com/sindresorhus/open
