### ISSUE TITLE
Combine existing Components

### ISSUE THREAD

**Issue by mindtheme** [amosproj/amos2022ss08-openid-connect-doctor#59]
### User Story
1. As an engineer
2. I need to be able to do actions in a pre-defined order
3. So that it is possible go from one action to the next one without reentering all information
### Acceptance Criteria
- Adjust frontend to request a token using client credential grant and the issuer provided in the endpoint analysis
- Decode the requested token and display it without having to enter additional information other than the credentials
### Definition of Done
- Code has been tested
- Optional Logging has been added
- No errors (syntax, unit tests, etc.)
- Peer reviewed by at least one additional person
- Acceptance criteria met
- The code was merged into the main branch via pull request

**Comment by prebbe** [comment]
I just updated the documentation and created a [PR](https://github.com/amosproj/amos2022ss08-openid-connect-doctor/pull/79) for the changes.

@raghunandanarava : Can you have a look at the changes as well?
