### ISSUE TITLE
Decode a JWT token

### ISSUE THREAD

**Issue by AnnaBilo** [amosproj/amos2022ss08-openid-connect-doctor#9]
### User Story
1. As a user
2. I need the program to decode a JWS & JWE token
3. So that I can read its content
### Acceptance Criteria
- A provided JWS or JWE token can be decoded
- The decoded token should be in a format readable by humans (JSON or similar)
- An example can be seen here https://jwt.io/

### Definition of Done

- Code has been tested
- Optional Logging has been added
- No errors (syntax, unit tests, etc.)
- Peer reviewed by at least one additional person
- Acceptance criteria met
- The code was merged into the main branch via pull request

**Comment by skriesch** [comment]
nestjs provides JWT functionality integrated, what we can use: https://docs.nestjs.com/security/authentication#jwt-functionality
The art is to decode.

**Comment by prebbe** [comment]
I would suggest we use a library that is related to the libraries we already use: https://github.com/panva/jose
I implemented a short prototype that can decode a provided token (JWS) and returns the included subject to the user (see the linked issue). If no one is against it, will continue to refine this functionality, so we can decode different tokens and return more values.

**Comment by skriesch** [comment]
That sounds good for me. At the and of the library documentation of jose, there is also the hint for node-jose. That has got also the decoding integrated: https://github.com/cisco/node-joseThis exposes _[urlsafe-base64](https://github.com/RGBboy/urlsafe-base64)'s encode and decode methods as encode and decode (respectively)._
